"""Constants module for KubEagle TUI.

Centralized constants organized by domain:
- enums.py: All Enum class definitions
- values.py: Scalar constants (strings, numbers with Final)
- timeouts.py: Timeout values (seconds)
- limits.py: Limit values (max/min)
- defaults.py: Default values for settings
- tables.py: Table column configurations
- screens/: Screen-specific constants

Note: Keyboard bindings are now defined in kubeagle.keyboard module.
"""

from kubeagle.constants.defaults import (
    ACTIVE_CHARTS_PATH_DEFAULT,
    AUTO_REFRESH_DEFAULT,
    CHARTS_PATH_DEFAULT,
    CODEOWNERS_PATH_DEFAULT,
    EVENT_AGE_HOURS_DEFAULT,
    EXPORT_PATH_DEFAULT,
    HIGH_CPU_THRESHOLD_DEFAULT,
    HIGH_MEMORY_THRESHOLD_DEFAULT,
    HIGH_POD_PERCENTAGE_THRESHOLD_DEFAULT,
    HIGH_POD_THRESHOLD_DEFAULT,
    LIMIT_REQUEST_RATIO_THRESHOLD_DEFAULT,
    REFRESH_INTERVAL_DEFAULT,
    THEME_DEFAULT,
    USE_CLUSTER_MODE_DEFAULT,
    USE_CLUSTER_VALUES_DEFAULT,
)
from kubeagle.constants.enums import (
    AppState,
    DataRefreshMode,
    FetchSources,
    FetchState,
    FilterOperator,
    LoadingState,
    NavigationMode,
    NodeStatus,
    QoSClass,
    Severity,
    SortDirection,
    SortField,
    TabState,
    ThemeMode,
)
from kubeagle.constants.limits import (
    DEFAULT_PAGE_SIZE,
    DEGRADED_THRESHOLD,
    HEALTHY_THRESHOLD,
    MAX_COLUMNS_DISPLAY,
    MAX_EVENTS_DISPLAY,
    MAX_FILTER_DEPTH,
    MAX_PAGE_SIZE,
    MAX_ROWS_DISPLAY,
    MIN_PAGE_SIZE,
    REFRESH_INTERVAL_MIN,
    THRESHOLD_MAX,
    THRESHOLD_MIN,
    WARNING_CPU_PERCENT,
    WARNING_MEMORY_PERCENT,
)
from kubeagle.constants.screens.cluster import (
    LOADING_ANALYZING,
    LOADING_CHECKING_CONNECTION,
    LOADING_FETCHING_EVENTS,
    LOADING_FETCHING_NODE_RESOURCES,
    LOADING_FETCHING_NODES,
    LOADING_FETCHING_PDBS,
    LOADING_FETCHING_SINGLE_REPLICA,
    LOADING_INITIALIZING,
    STATUS_LABEL_CLUSTER,
    STATUS_LABEL_NODES,
    STATUS_LABEL_UPDATED,
    STATUS_NEVER,
    STATUS_UNKNOWN,
    TAB_EVENTS,
    TAB_GROUPS,
    TAB_HEALTH,
    TAB_IDS,
    TAB_NODE_DIST,
    TAB_NODES,
    TAB_OVERVIEW,
    TAB_PDBS,
    TAB_PODS,
    TAB_SINGLE_REPLICA,
    TAB_STATS,
)
from kubeagle.constants.screens.common import (
    DARK_THEME,
    DEFAULT_THEME,
    INSIDERONE_DARK_THEME,
    LIGHT_THEME,
)
from kubeagle.constants.tables import (
    CLUSTER_EVENTS_COLUMNS,
    CLUSTER_NODE_DIST_COLUMNS,
    CLUSTER_NODE_GROUPS_COLUMNS,
    CLUSTER_NODES_COLUMNS,
    CLUSTER_PDBS_COLUMNS,
    CLUSTER_PODS_COLUMNS,
    CLUSTER_SINGLE_REPLICA_COLUMNS,
    CLUSTER_STATS_COLUMNS,
    ColumnWidth,
)
from kubeagle.constants.timeouts import (
    CLUSTER_CHECK_TIMEOUT,
    CLUSTER_REQUEST_TIMEOUT,
    DEFAULT_TIMEOUT,
    LONG_TIMEOUT,
    NODE_FETCH_TIMEOUT,
    NODE_GROUPS_TIMEOUT,
    SHORT_TIMEOUT,
    STATUS_UPDATE_INTERVAL,
    VIOLATION_CHECK_TIMEOUT,
)
from kubeagle.constants.values import (
    APP_TITLE,
    COLOR_ACCENT,
    COLOR_ERROR,
    COLOR_PRIMARY,
    COLOR_SECONDARY,
    COLOR_SUCCESS,
    COLOR_WARNING,
    MAX_CACHE_AGE_SECONDS,
    SPACING,
    STATUS_CONNECTED,
    STATUS_DISCONNECTED,
    STATUS_LOADING,
    TABLE_PAGE_SIZE,
)

__all__ = [
    # Application
    "APP_TITLE",
    # Colors
    "COLOR_PRIMARY",
    "COLOR_SECONDARY",
    "COLOR_ACCENT",
    "COLOR_SUCCESS",
    "COLOR_WARNING",
    "COLOR_ERROR",
    # Layout
    "SPACING",
    # Data
    "TABLE_PAGE_SIZE",
    # Status
    "STATUS_DISCONNECTED",
    "STATUS_CONNECTED",
    "STATUS_LOADING",
    # Cache
    "MAX_CACHE_AGE_SECONDS",
    # Timeouts
    "CLUSTER_REQUEST_TIMEOUT",
    "DEFAULT_TIMEOUT",
    "LONG_TIMEOUT",
    "SHORT_TIMEOUT",
    "CLUSTER_CHECK_TIMEOUT",
    "NODE_FETCH_TIMEOUT",
    "NODE_GROUPS_TIMEOUT",
    "VIOLATION_CHECK_TIMEOUT",
    "STATUS_UPDATE_INTERVAL",
    # Limits
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "MIN_PAGE_SIZE",
    "MAX_ROWS_DISPLAY",
    "MAX_COLUMNS_DISPLAY",
    "MAX_FILTER_DEPTH",
    "MAX_EVENTS_DISPLAY",
    "HEALTHY_THRESHOLD",
    "DEGRADED_THRESHOLD",
    "WARNING_CPU_PERCENT",
    "WARNING_MEMORY_PERCENT",
    "REFRESH_INTERVAL_MIN",
    "THRESHOLD_MIN",
    "THRESHOLD_MAX",
    # Defaults
    "CHARTS_PATH_DEFAULT",
    "ACTIVE_CHARTS_PATH_DEFAULT",
    "CODEOWNERS_PATH_DEFAULT",
    "EXPORT_PATH_DEFAULT",
    "THEME_DEFAULT",
    "REFRESH_INTERVAL_DEFAULT",
    "AUTO_REFRESH_DEFAULT",
    "USE_CLUSTER_VALUES_DEFAULT",
    "USE_CLUSTER_MODE_DEFAULT",
    "EVENT_AGE_HOURS_DEFAULT",
    "HIGH_CPU_THRESHOLD_DEFAULT",
    "HIGH_MEMORY_THRESHOLD_DEFAULT",
    "HIGH_POD_THRESHOLD_DEFAULT",
    "LIMIT_REQUEST_RATIO_THRESHOLD_DEFAULT",
    "HIGH_POD_PERCENTAGE_THRESHOLD_DEFAULT",
    # Enums
    "AppState",
    "LoadingState",
    "FetchState",
    "FetchSources",
    "TabState",
    "NodeStatus",
    "QoSClass",
    "Severity",
    "ThemeMode",
    "SortDirection",
    "FilterOperator",
    "DataRefreshMode",
    "NavigationMode",
    "SortField",
    # Tables
    "ColumnWidth",
    "CLUSTER_NODES_COLUMNS",
    "CLUSTER_PODS_COLUMNS",
    "CLUSTER_EVENTS_COLUMNS",
    "CLUSTER_PDBS_COLUMNS",
    "CLUSTER_SINGLE_REPLICA_COLUMNS",
    "CLUSTER_NODE_DIST_COLUMNS",
    "CLUSTER_NODE_GROUPS_COLUMNS",
    "CLUSTER_STATS_COLUMNS",
    # Screen constants
    "TAB_IDS",
    "TAB_OVERVIEW",
    "TAB_NODES",
    "TAB_PODS",
    "TAB_EVENTS",
    "TAB_PDBS",
    "TAB_SINGLE_REPLICA",
    "TAB_HEALTH",
    "TAB_NODE_DIST",
    "TAB_GROUPS",
    "TAB_STATS",
    "STATUS_LABEL_CLUSTER",
    "STATUS_LABEL_NODES",
    "STATUS_LABEL_UPDATED",
    "STATUS_NEVER",
    "STATUS_UNKNOWN",
    "LOADING_INITIALIZING",
    "LOADING_CHECKING_CONNECTION",
    "LOADING_FETCHING_NODES",
    "LOADING_FETCHING_EVENTS",
    "LOADING_FETCHING_SINGLE_REPLICA",
    "LOADING_FETCHING_PDBS",
    "LOADING_FETCHING_NODE_RESOURCES",
    "LOADING_ANALYZING",
    # Themes
    "DARK_THEME",
    "LIGHT_THEME",
    "INSIDERONE_DARK_THEME",
    "DEFAULT_THEME",
]
