"""Optimizer threshold constants."""

LIMIT_REQUEST_RATIO_THRESHOLD = 2.0
LOW_CPU_THRESHOLD_MILLICORES = 10
LOW_MEMORY_THRESHOLD_MI = 32
PDB_BLOCKING_THRESHOLD = 1

__all__ = [
    "LIMIT_REQUEST_RATIO_THRESHOLD",
    "LOW_CPU_THRESHOLD_MILLICORES",
    "LOW_MEMORY_THRESHOLD_MI",
    "PDB_BLOCKING_THRESHOLD",
]
