"""Screen-specific constants subpackage.

Re-exports all screen-specific constants for convenient imports.
"""

from kubeagle.constants.screens.charts_explorer import (
    CHARTS_EXPLORER_TITLE,
)
from kubeagle.constants.screens.cluster import (
    CLUSTER_ERROR_LOADING,
    CLUSTER_EVENT_WINDOW_DEFAULT,
    CLUSTER_EVENT_WINDOW_OPTIONS,
    LOADING_ANALYZING,
    LOADING_CHECKING_CONNECTION,
    LOADING_FETCHING_EVENTS,
    LOADING_FETCHING_NODE_RESOURCES,
    LOADING_FETCHING_NODES,
    LOADING_FETCHING_PDBS,
    LOADING_FETCHING_SINGLE_REPLICA,
    LOADING_INITIALIZING,
    STATUS_LABEL_CLUSTER,
    STATUS_LABEL_NODES,
    STATUS_LABEL_UPDATED,
    STATUS_NEVER,
    STATUS_UNKNOWN,
    TAB_EVENTS,
    TAB_GROUPS,
    TAB_HEALTH,
    TAB_IDS,
    TAB_NODE_DIST,
    TAB_NODES,
    TAB_OVERVIEW,
    TAB_PDBS,
    TAB_PODS,
    TAB_SINGLE_REPLICA,
    TAB_STATS,
)
from kubeagle.constants.screens.common import (
    DARK_THEME,
    DEFAULT_THEME,
    INSIDERONE_DARK_THEME,
    LIGHT_THEME,
)
from kubeagle.constants.screens.detail import (
    OPTIMIZER_CATEGORIES,
    OPTIMIZER_SEVERITIES,
)
from kubeagle.constants.screens.settings import (
    SETTINGS_SECTION_AI_FIX,
    SETTINGS_SECTION_CLUSTER,
    SETTINGS_SECTION_GENERAL,
    SETTINGS_SECTION_THRESHOLDS,
    SETTINGS_VALIDATION_MESSAGES,
)

__all__ = [
    # Cluster
    "TAB_IDS",
    "TAB_OVERVIEW",
    "TAB_NODES",
    "TAB_PODS",
    "TAB_EVENTS",
    "TAB_PDBS",
    "TAB_SINGLE_REPLICA",
    "TAB_HEALTH",
    "TAB_NODE_DIST",
    "TAB_GROUPS",
    "TAB_STATS",
    "STATUS_LABEL_CLUSTER",
    "STATUS_LABEL_NODES",
    "STATUS_LABEL_UPDATED",
    "STATUS_NEVER",
    "STATUS_UNKNOWN",
    "LOADING_INITIALIZING",
    "LOADING_CHECKING_CONNECTION",
    "LOADING_FETCHING_NODES",
    "LOADING_FETCHING_EVENTS",
    "LOADING_FETCHING_SINGLE_REPLICA",
    "LOADING_FETCHING_PDBS",
    "LOADING_FETCHING_NODE_RESOURCES",
    "LOADING_ANALYZING",
    "CLUSTER_ERROR_LOADING",
    "CLUSTER_EVENT_WINDOW_OPTIONS",
    "CLUSTER_EVENT_WINDOW_DEFAULT",
    # Charts Explorer
    "CHARTS_EXPLORER_TITLE",
    # Settings
    "SETTINGS_SECTION_GENERAL",
    "SETTINGS_SECTION_THRESHOLDS",
    "SETTINGS_SECTION_AI_FIX",
    "SETTINGS_SECTION_CLUSTER",
    "SETTINGS_VALIDATION_MESSAGES",
    # Detail
    "OPTIMIZER_CATEGORIES",
    "OPTIMIZER_SEVERITIES",
    # Themes
    "DARK_THEME",
    "LIGHT_THEME",
    "INSIDERONE_DARK_THEME",
    "DEFAULT_THEME",
]
